wargame:
  build: .
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock:ro
    - /usr/bin/docker:/usr/bin/docker:ro
    - /usr/bin/rancher-compose:/usr/bin/rancher-compose:ro
    - /lib/x86_64-linux-gnu/libsystemd-journal.so.0:/lib/x86_64-linux-gnu/libsystemd-journal.so.0:ro
    - /usr/bin/protoc:/usr/bin/protoc:ro
    - /usr/bin/node:/usr/bin/node:ro
    - /usr/bin/npm:/user/bin/npm:ro
  environment:
    - PD_DATABASE_HOST=$DB_HOST
    - PD_DATABASE_USER=$DB_USER
    - PD_DATABASE_PASSWORD=$DB_PASS
    - PD_DATABASE_NAME=$DB_NAME
    - DEVISE_SECRET_KEY=$DEVISE_KEY
    - MAIL_SENDER=$MAIL_SENDER
    - MAIL_USERNAME=$MAIL_USERNAME
    - MAIL_PASSWORD=$MAIL_PASSWORD
    - APP_ID=$APP_ID
    - APP_SECRET=$APP_SECRET
    - RANCHER_URL=$RANCHER_URL
    - RANCHER_ACCESS_KEY=$RANCHER_ACCESS_KEY
    - RANCHER_SECRET_KEY=$RANCHER_SECRET_KEY
  ports:
    - "80:80"
    - "443:443"
