development:
  address: "smtp.gmail.com"
  port: 587
  domain: "gmail.com"
  authentication: "plain"
  user_name: "example@gmail.com"
  password: "123456"
  enable_starttls_auto: true
production:
  address: "smtp.sendgrid.net"
  port: 587
  domain: "domain.com"
  authentication: "plain"
  user_name: <%= ENV["MAIL_USERNAME"] %>
  password: <%= ENV["MAIL_PASSWORD"] %>
  enable_starttls_auto: true
