# Options here can still be overridden by cmd line args.
#   sidekiq -C sidekiq.yml
---
:concurrency: 20
:pidfile: tmp/pids/sidekiq.pid
:logfile: log/sidekiq.log
:queues:
  - [docker_assignment, 2]
  - default
development:
  :queues:
    - [docker_assignment, 2]
    - default
production:
  :queues:
    - [docker_assignment, 2]
    - default
